"""Tests comparing jaxrate's phylogenetic EM against xrate's expected counts and updated parameters.

Reference data was generated by running xrate (from github.com/ihh/dart) on each
grammar + alignment combination with 1 EM round and zero pseudocounts:

    xrate -g <grammar.eg> -t <out.eg> --maxrounds 1 -pi 0 -pm 0 -pt 0 -q <alignment.sto>

For each test case we verify:
    1. Expected substitution counts (wait times, mutation counts) match
    2. Updated rate matrix Q matches after one M-step
    3. Updated equilibrium distribution pi matches
    4. Updated rule probabilities match

Tolerance: rtol=5e-3 (0.5%) accounts for minor numerical differences between
xrate's Newmat eigendecomposition and JAX/subby's implementation.
"""

import os
import math
import pytest
import numpy as np

import jax
jax.config.update('jax_enable_x64', True)
import jax.numpy as jnp

from subby.formats import parse_newick, parse_stockholm
from subby.jax.types import Tree
from subby.jax import LogLike, Counts, RootProb
from subby.jax.models import model_from_rate_matrix

from jaxrate import (
    parse_xrate_file, compile_grammar, inside, viterbi,
    TerminalWeights,
)
from jaxrate.phylo_model import (
    PhyloModel, phylo_em_step, _m_step_rules, _stationary_dist,
)


DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'jaxrate', 'data')

# Tolerance for floating-point comparisons between JAX eigensolver and
# xrate's Newmat Jacobi eigensolver
RTOL = 5e-3


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_alignment_with_tree(sto_path, alphabet):
    """Load a Stockholm alignment that has an embedded tree."""
    with open(sto_path) as f:
        text = f.read()
    sto = parse_stockholm(text, alphabet=alphabet)
    if hasattr(sto, 'alignment'):
        alignment = sto.alignment
        tree = Tree(
            parentIndex=jnp.array(sto.tree.parentIndex, dtype=jnp.int32),
            distanceToParent=jnp.array(sto.tree.distanceToParent, dtype=jnp.float64),
        )
        return alignment, tree, sto.leaf_names
    raise ValueError("Stockholm file has no embedded tree")


def _load_alignment_with_newick(sto_path, newick, alphabet):
    """Load alignment + tree from separate Stockholm and Newick string."""
    with open(sto_path) as f:
        text = f.read()
    sto = parse_stockholm(text, alphabet=alphabet)
    if isinstance(sto, dict):
        alignment_raw = sto['alignment']
        leaf_names_sto = sto['leaf_names']
    else:
        alignment_raw = sto.alignment
        leaf_names_sto = sto.leaf_names

    tree_result = parse_newick(newick)
    tree = Tree(
        parentIndex=jnp.array(tree_result['parentIndex'], dtype=jnp.int32),
        distanceToParent=jnp.array(tree_result['distanceToParent'], dtype=jnp.float64),
    )

    R = len(tree_result['parentIndex'])
    C = alignment_raw.shape[1]
    gap_token = len(alphabet) + 1
    full_alignment = np.full((R, C), gap_token, dtype=np.int32)

    name_to_row = {name: i for i, name in enumerate(leaf_names_sto)}
    for node_idx in range(R):
        node_name = tree_result['node_names'][node_idx]
        if node_name is not None and node_name in name_to_row:
            full_alignment[node_idx] = alignment_raw[name_to_row[node_name]]

    return full_alignment, tree, leaf_names_sto


def _compute_subby_counts(alignment, tree, Q, pi, reversible=True):
    """Compute expected counts using subby, symmetrizing for reversible models."""
    model = model_from_rate_matrix(
        jnp.array(Q, dtype=jnp.float64),
        jnp.array(pi, dtype=jnp.float64),
        reversible=reversible,
    )
    alignment_jnp = jnp.array(alignment, dtype=jnp.int32)

    counts = Counts(alignment_jnp, tree, model)
    total = np.array(jnp.sum(counts, axis=-1))

    A = Q.shape[0]
    if reversible:
        for i in range(A):
            for j in range(i + 1, A):
                avg = (total[i, j] + total[j, i]) / 2
                total[i, j] = avg
                total[j, i] = avg

    root_post = RootProb(alignment_jnp, tree, model)
    init = np.array(jnp.sum(root_post, axis=-1))

    return {
        'waits': np.diag(total),
        'mutations': total,
        'inits': init,
    }


def _m_step_rates(waits, mutations, A, pseudocounts=0.0):
    """Apply the M-step to get updated Q from expected counts."""
    w = waits.copy() + pseudocounts
    u = mutations.copy()
    np.fill_diagonal(u, 0)
    new_Q = u / np.maximum(w[:, None], 1e-30)
    np.fill_diagonal(new_Q, 0)
    np.fill_diagonal(new_Q, -new_Q.sum(axis=1))
    return new_Q


# ---------------------------------------------------------------------------
# Test Case 1: Tiny JC model (gap-free, 3 seqs, 5 cols, RNA)
# Reference: xrate -g tiny_jc.eg -t out.eg --maxrounds 1 -pi 0 -pm 0 -pt 0
# ---------------------------------------------------------------------------

class TestXrateJC:
    """Compare with xrate on a Jukes-Cantor model (simplest possible case)."""

    # xrate reference values
    XRATE_WAITS = [0.669984, 0.654324, 0.653994, 0.523897]
    XRATE_MUTS_SYM = {
        (0, 1): 0.499498, (0, 2): 0.499521, (0, 3): 0.220944,
        (1, 2): 0.392343, (1, 3): 0.213111, (2, 3): 0.213074,
    }
    XRATE_INITS = [1.36008, 1.18476, 1.39118, 1.06686]
    XRATE_UPDATED_RATES = {
        (0, 1): 0.745536, (0, 2): 0.745571, (0, 3): 0.329775,
        (1, 0): 0.76338, (1, 2): 0.599615, (1, 3): 0.325697,
        (2, 0): 0.7638, (2, 1): 0.599918, (2, 3): 0.325804,
        (3, 0): 0.421733, (3, 1): 0.406781, (3, 2): 0.406709,
    }
    XRATE_RULES = {'S*->': 0.200129, 'S*->S': 0.800515}

    @pytest.fixture
    def setup(self):
        alignment, tree, _ = _load_alignment_with_tree(
            os.path.join(DATA_DIR, 'tiny_test.sto'),
            alphabet=['A', 'C', 'G', 'U'],
        )
        A = 4
        Q = np.ones((A, A)) * 1.0
        np.fill_diagonal(Q, -3.0)
        pi = np.ones(A) / A
        return alignment, tree, Q, pi

    def test_wait_times(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        np.testing.assert_allclose(result['waits'], self.XRATE_WAITS, rtol=RTOL)

    def test_mutation_counts(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        for (i, j), xr_val in self.XRATE_MUTS_SYM.items():
            np.testing.assert_allclose(
                result['mutations'][i, j], xr_val, rtol=RTOL,
                err_msg=f"mut[{i},{j}]")

    def test_init_counts(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        np.testing.assert_allclose(result['inits'], self.XRATE_INITS, rtol=RTOL)

    def test_m_step_rates(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        new_Q = _m_step_rates(result['waits'], result['mutations'], 4)
        for (i, j), xr_val in self.XRATE_UPDATED_RATES.items():
            np.testing.assert_allclose(
                new_Q[i, j], xr_val, rtol=RTOL,
                err_msg=f"rate[{i},{j}]")

    def test_m_step_row_sums_zero(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        new_Q = _m_step_rates(result['waits'], result['mutations'], 4)
        np.testing.assert_allclose(new_Q.sum(axis=1), 0, atol=1e-10)

    def test_integrated_em_rates(self, setup):
        """PhyloModel EM step produces rates matching xrate."""
        alignment, tree, Q, pi = setup
        xg = parse_xrate_file(os.path.join(DATA_DIR, 'tiny_jc.eg'))
        pm = PhyloModel(
            grammar=xg.grammar, alignment=alignment, tree=tree,
            chains=[{'rate_matrix': Q.copy(), 'pi': pi.copy(),
                     'update_policy': 'rev'}],
        )
        phylo_em_step(pm, fit_rules=False, fit_rates=True, fit_pi=True,
                      pseudocounts=0.0)
        new_Q = pm.chains[0]['rate_matrix']
        for (i, j), xr_val in self.XRATE_UPDATED_RATES.items():
            np.testing.assert_allclose(
                new_Q[i, j], xr_val, rtol=RTOL,
                err_msg=f"em rate[{i},{j}]")

    def test_integrated_em_rules(self, setup):
        """PhyloModel EM step produces rule probs matching xrate."""
        alignment, tree, Q, pi = setup
        xg = parse_xrate_file(os.path.join(DATA_DIR, 'tiny_jc.eg'))
        pm = PhyloModel(
            grammar=xg.grammar, alignment=alignment, tree=tree,
            chains=[{'rate_matrix': Q.copy(), 'pi': pi.copy(),
                     'update_policy': 'rev'}],
        )
        phylo_em_step(pm, fit_rules=True, fit_rates=False, fit_pi=False,
                      pseudocounts=0.0)
        for rule in pm.grammar.rules:
            nt_name = pm.grammar.nonterminals[rule.lhs].name
            rhs_names = ' '.join(pm.grammar.nonterminals[r].name
                                 for r in rule.rhs)
            key = f"{nt_name}->{rhs_names}"
            if key in self.XRATE_RULES:
                np.testing.assert_allclose(
                    math.exp(rule.log_weight), self.XRATE_RULES[key],
                    rtol=RTOL, err_msg=f"rule {key}")


# ---------------------------------------------------------------------------
# Test Case 2: nullrna HMM (trimmed RF00390, gap-free, 7 seqs, 23 cols)
# Reference: xrate -g nullrna.eg -t out.eg --maxrounds 1 -pi 0 -pm 0 -pt 0
# ---------------------------------------------------------------------------

class TestXrateNullRNA:
    """Compare with xrate nullrna grammar on trimmed RF00390."""

    NEWICK = ("((J04373.1/6212-6234:0.0001000000,"
              "(M24803.1/1-23:0.0001000000,"
              "(M24805.1/67-89:0.0001000000,"
              "(AF035635.1/619-641:0.0001000000,"
              "M24804.1/82-104:0.0496150874)node_7:0.0069023410"
              ")node_8:0.0447606013"
              ")node_9:0.0417514257"
              ")node_10:0.0001000000,"
              "(M24801.1/79-101:0.0001000000,"
              "URS0000E60B65_12154/1-26:0.0001000000"
              ")node_11:0.0001000000)root;")

    XRATE_WAITS = [0.928372, 0.698302, 0.485817, 1.19722]
    XRATE_MUTS_SYM = {
        (0, 1): 0.00245273, (0, 2): 0.506309, (0, 3): 0.0123199,
        (1, 2): 0.00793564, (1, 3): 0.522529, (2, 3): 0.498834,
    }
    XRATE_UPDATED_RATES = {
        (0, 1): 0.00264197, (0, 2): 0.545373, (0, 3): 0.0132704,
        (1, 0): 0.00351243, (1, 2): 0.0113642, (1, 3): 0.748286,
        (2, 0): 1.04218, (2, 1): 0.0163346, (2, 3): 1.02679,
        (3, 0): 0.0102904, (3, 1): 0.436452, (3, 2): 0.416661,
    }
    XRATE_RULES = {'S*->': 0.0434952, 'S*->S': 0.956608}

    @pytest.fixture
    def setup(self):
        alignment, tree, _ = _load_alignment_with_tree(
            os.path.join(DATA_DIR, 'RF00390_trim.sto'),
            alphabet=['A', 'C', 'G', 'U'],
        )
        xg = parse_xrate_file(os.path.join(DATA_DIR, 'nullrna.eg'))
        chain = xg.get_single_models()[0]
        Q = np.array(chain['rate_matrix'])
        pi = np.array(chain['pi'])
        return alignment, tree, Q, pi, xg

    def test_wait_times(self, setup):
        alignment, tree, Q, pi, _ = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        np.testing.assert_allclose(result['waits'], self.XRATE_WAITS, rtol=RTOL)

    def test_mutation_counts(self, setup):
        alignment, tree, Q, pi, _ = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        for (i, j), xr_val in self.XRATE_MUTS_SYM.items():
            np.testing.assert_allclose(
                result['mutations'][i, j], xr_val, rtol=RTOL,
                err_msg=f"mut[{i},{j}]")

    def test_m_step_rates(self, setup):
        alignment, tree, Q, pi, _ = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        new_Q = _m_step_rates(result['waits'], result['mutations'], 4)
        for (i, j), xr_val in self.XRATE_UPDATED_RATES.items():
            np.testing.assert_allclose(
                new_Q[i, j], xr_val, rtol=RTOL,
                err_msg=f"rate[{i},{j}]")

    def test_stationary_pi(self, setup):
        alignment, tree, Q, pi, _ = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        new_Q = _m_step_rates(result['waits'], result['mutations'], 4)
        new_pi = _stationary_dist(new_Q)
        assert new_pi is not None
        np.testing.assert_allclose(new_pi.sum(), 1.0, atol=1e-10)
        np.testing.assert_allclose(new_pi @ new_Q, 0, atol=1e-8)

    def test_integrated_em_rates(self, setup):
        """PhyloModel EM step rates match xrate on nullrna."""
        alignment, tree, Q, pi, xg = setup
        pm = PhyloModel(
            grammar=xg.grammar, alignment=alignment, tree=tree,
            chains=[{'rate_matrix': Q.copy(), 'pi': pi.copy(),
                     'update_policy': 'rev'}],
        )
        phylo_em_step(pm, fit_rules=False, fit_rates=True, fit_pi=True,
                      pseudocounts=0.0)
        new_Q = pm.chains[0]['rate_matrix']
        for (i, j), xr_val in self.XRATE_UPDATED_RATES.items():
            np.testing.assert_allclose(
                new_Q[i, j], xr_val, rtol=RTOL,
                err_msg=f"em rate[{i},{j}]")

    def test_integrated_em_rules(self, setup):
        """PhyloModel EM step rule probs match xrate on nullrna."""
        alignment, tree, Q, pi, xg = setup
        pm = PhyloModel(
            grammar=xg.grammar, alignment=alignment, tree=tree,
            chains=[{'rate_matrix': Q.copy(), 'pi': pi.copy(),
                     'update_policy': 'rev'}],
        )
        phylo_em_step(pm, fit_rules=True, fit_rates=False, fit_pi=False,
                      pseudocounts=0.0)
        for rule in pm.grammar.rules:
            nt_name = pm.grammar.nonterminals[rule.lhs].name
            rhs_names = ' '.join(pm.grammar.nonterminals[r].name
                                 for r in rule.rhs)
            key = f"{nt_name}->{rhs_names}"
            if key in self.XRATE_RULES:
                np.testing.assert_allclose(
                    math.exp(rule.log_weight), self.XRATE_RULES[key],
                    rtol=2e-2, err_msg=f"rule {key}")


# ---------------------------------------------------------------------------
# Test Case 3: nullprot HMM (protein, 20x20 rate matrix, 4 seqs, 7 cols)
# Reference: xrate -g nullprot.eg -t out.eg --maxrounds 1 -pi 0 -pm 0 -pt 0
# ---------------------------------------------------------------------------

class TestXrateNullProt:
    """Compare with xrate nullprot grammar on a 4-seq protein alignment."""

    PROT_ALPHABET = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G',
                     'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S',
                     'T', 'W', 'Y', 'V']

    # Spot-check wait times (state index: xrate value)
    XRATE_WAITS_SELECT = {
        0: 0.0580383,   # A (Ala)
        9: 0.489495,    # I (Ile)
        10: 0.500327,   # L (Leu)
        16: 0.440419,   # T (Thr)
    }

    @pytest.fixture
    def setup(self):
        alignment, tree, _ = _load_alignment_with_tree(
            os.path.join(DATA_DIR, 'prot_test.sto'),
            alphabet=self.PROT_ALPHABET,
        )
        xg = parse_xrate_file(os.path.join(DATA_DIR, 'nullprot.eg'))
        chain = xg.get_single_models()[0]
        Q = np.array(chain['rate_matrix'])
        pi = np.array(chain['pi'])
        return alignment, tree, Q, pi

    def test_wait_times_spot_check(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        for idx, xr_val in self.XRATE_WAITS_SELECT.items():
            np.testing.assert_allclose(
                result['waits'][idx], xr_val, rtol=RTOL,
                err_msg=f"wait[{idx}]")

    def test_counts_shape(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        assert result['waits'].shape == (20,)
        assert result['mutations'].shape == (20, 20)
        assert result['inits'].shape == (20,)

    def test_m_step_valid(self, setup):
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi)
        new_Q = _m_step_rates(result['waits'], result['mutations'], 20)
        np.testing.assert_allclose(new_Q.sum(axis=1), 0, atol=1e-10)
        new_pi = _stationary_dist(new_Q)
        assert new_pi is not None
        np.testing.assert_allclose(new_pi.sum(), 1.0, atol=1e-10)

    def test_symmetry_for_reversible(self, setup):
        """Off-diagonal counts should be symmetric for reversible model."""
        alignment, tree, Q, pi = setup
        result = _compute_subby_counts(alignment, tree, Q, pi, reversible=True)
        muts = result['mutations'].copy()
        np.fill_diagonal(muts, 0)
        np.testing.assert_allclose(muts, muts.T, atol=1e-10)


# ---------------------------------------------------------------------------
# Test Case 4: pfold SCFG — verify Viterbi + single-chain raw counts
# The grammar-weighted chain counts require the full integrated EM;
# here we just verify the raw (unweighted) single-chain phylogenetic counts
# and Viterbi decoding.
# ---------------------------------------------------------------------------

class TestXratePfold:
    """Compare pfold SCFG components against xrate."""

    NEWICK = ("((J04373.1/6212-6234:0.0001000000,"
              "(M24803.1/1-23:0.0001000000,"
              "(M24805.1/67-89:0.0001000000,"
              "(AF035635.1/619-641:0.0001000000,"
              "M24804.1/82-104:0.0496150874)node_7:0.0069023410"
              ")node_8:0.0447606013"
              ")node_9:0.0417514257"
              ")node_10:0.0001000000,"
              "(M24801.1/79-101:0.0001000000,"
              "URS0000E60B65_12154/1-26:0.0001000000"
              ")node_11:0.0001000000)root;")

    @pytest.fixture
    def setup(self):
        alignment, tree, _ = _load_alignment_with_tree(
            os.path.join(DATA_DIR, 'RF00390_trim.sto'),
            alphabet=['A', 'C', 'G', 'U'],
        )
        xg = parse_xrate_file(os.path.join(DATA_DIR, 'pfold.eg'))
        return alignment, tree, xg

    def test_viterbi_runs(self, setup):
        alignment, tree, xg = setup
        pm = PhyloModel.from_xrate(xg, alignment, tree)
        tw = pm.terminal_weights()
        labels, log_prob = viterbi(xg.grammar, tw)
        assert labels.shape[0] == alignment.shape[1]
        assert jnp.isfinite(log_prob)

    def test_single_chain_raw_counts(self, setup):
        """Raw (unweighted) NUC chain counts should match xrate's
        nullrna counts on the same alignment+tree, since nullrna uses
        the same NUC chain structure."""
        alignment, tree, xg = setup
        chain = xg.get_single_models()[0]
        Q = np.array(chain['rate_matrix'])
        pi = np.array(chain['pi'])
        result = _compute_subby_counts(alignment, tree, Q, pi)
        # These are raw counts (all columns weighted equally).
        # Just verify they're finite and positive.
        assert np.all(np.isfinite(result['waits']))
        assert np.all(result['waits'] > 0)


# ---------------------------------------------------------------------------
# Test Case 5: Two-state phylo-HMM (slow/fast, multi-chain, xrate S/S* pattern)
# This is the critical test for HMM forward-backward with state-specific
# emission models. Unlike the null models above, this exercises:
#   - Per-state model posteriors (forward-backward assigns columns to chains)
#   - Null-state elimination (xrate's S→emit S*, S*→transition pattern)
#   - Multi-chain rate M-step (each chain weighted by its state's posteriors)
#   - Rule weight M-step for transition probabilities between states
# Reference: xrate -g two_state_hmm.eg -t out.eg --maxrounds 1 -pi 0 -pm 0 -pt 0
# ---------------------------------------------------------------------------

class TestXrateTwoStateHMM:
    """Compare 2-state phylo-HMM (slow/fast) against xrate."""

    # xrate reference: updated rules after 1 EM round
    XRATE_RULES = {
        'SLOW_S*->SLOW_S': 0.90125, 'SLOW_S*->FAST_S': 0.0304799,
        'SLOW_S*->': 0.068726,
        'FAST_S*->FAST_S': 0.407254, 'FAST_S*->SLOW_S': 0.567228,
        'FAST_S*->': 0.0257372,
    }

    # xrate reference: updated rates after 1 EM round
    XRATE_SLOW_RATES = {
        (0, 1): 0.0908169, (0, 2): 0.422364, (0, 3): 0.600034,
        (1, 0): 0.0959254, (1, 2): 0.307742, (1, 3): 0.828989,
        (2, 0): 0.357707, (2, 1): 0.246752, (2, 3): 0.0814067,
        (3, 0): 0.564786, (3, 1): 0.738736, (3, 2): 0.0904747,
    }
    XRATE_FAST_RATES = {
        (0, 1): 2.07708, (0, 2): 2.35092, (0, 3): 2.89776,
        (1, 0): 3.15221, (1, 2): 2.61651, (1, 3): 3.75696,
        (2, 0): 3.81279, (2, 1): 2.79619, (2, 3): 3.34509,
        (3, 0): 2.87688, (3, 1): 2.45773, (3, 2): 2.04768,
    }

    # xrate reference: expected chain counts
    XRATE_SLOW_WAITS = [2.38511, 2.25809, 2.81623, 2.53397]
    XRATE_FAST_WAITS = [0.156381, 0.103043, 0.0964223, 0.157515]

    @pytest.fixture
    def setup(self):
        alignment, tree, _ = _load_alignment_with_tree(
            os.path.join(DATA_DIR, 'hmm_test.sto'),
            alphabet=['A', 'C', 'G', 'U'],
        )
        xg = parse_xrate_file(os.path.join(DATA_DIR, 'two_state_hmm.eg'))
        return alignment, tree, xg

    def test_log_likelihood(self, setup):
        alignment, tree, xg = setup
        pm = PhyloModel.from_xrate(xg, alignment, tree)
        tw = pm.terminal_weights()
        _, ll = inside(xg.grammar, tw)
        ll_bits = float(ll) / math.log(2)
        np.testing.assert_allclose(ll_bits, -99.8657, atol=0.05)

    def test_em_rules(self, setup):
        """Rule updates match xrate after one EM step."""
        alignment, tree, xg = setup
        pm = PhyloModel.from_xrate(xg, alignment, tree)
        phylo_em_step(pm, fit_rules=True, fit_rates=False, fit_pi=False,
                      pseudocounts=0.0)
        for rule in pm.grammar.rules:
            nt = pm.grammar.nonterminals[rule.lhs].name
            rhs = ' '.join(pm.grammar.nonterminals[r].name for r in rule.rhs)
            key = f"{nt}->{rhs}" if rhs else f"{nt}->"
            if key in self.XRATE_RULES:
                np.testing.assert_allclose(
                    math.exp(rule.log_weight), self.XRATE_RULES[key],
                    rtol=RTOL, err_msg=f"rule {key}")

    def test_em_slow_rates(self, setup):
        """Slow chain rates match xrate after one EM step."""
        alignment, tree, xg = setup
        pm = PhyloModel.from_xrate(xg, alignment, tree)
        phylo_em_step(pm, fit_rules=False, fit_rates=True, fit_pi=True,
                      pseudocounts=0.0)
        Q_slow = pm.chains[0]['rate_matrix']
        for (i, j), xr_val in self.XRATE_SLOW_RATES.items():
            np.testing.assert_allclose(
                Q_slow[i, j], xr_val, rtol=RTOL,
                err_msg=f"slow rate[{i},{j}]")

    def test_em_fast_rates(self, setup):
        """Fast chain rates match xrate after one EM step."""
        alignment, tree, xg = setup
        pm = PhyloModel.from_xrate(xg, alignment, tree)
        phylo_em_step(pm, fit_rules=False, fit_rates=True, fit_pi=True,
                      pseudocounts=0.0)
        Q_fast = pm.chains[1]['rate_matrix']
        for (i, j), xr_val in self.XRATE_FAST_RATES.items():
            np.testing.assert_allclose(
                Q_fast[i, j], xr_val, rtol=RTOL,
                err_msg=f"fast rate[{i},{j}]")

    def test_slow_chain_row_sums(self, setup):
        alignment, tree, xg = setup
        pm = PhyloModel.from_xrate(xg, alignment, tree)
        phylo_em_step(pm, fit_rules=False, fit_rates=True, fit_pi=True,
                      pseudocounts=0.0)
        np.testing.assert_allclose(
            pm.chains[0]['rate_matrix'].sum(axis=1), 0, atol=1e-10)

    def test_fast_chain_row_sums(self, setup):
        alignment, tree, xg = setup
        pm = PhyloModel.from_xrate(xg, alignment, tree)
        phylo_em_step(pm, fit_rules=False, fit_rates=True, fit_pi=True,
                      pseudocounts=0.0)
        np.testing.assert_allclose(
            pm.chains[1]['rate_matrix'].sum(axis=1), 0, atol=1e-10)


# ---------------------------------------------------------------------------
# Test Case 5: Detailed balance after M-step
# ---------------------------------------------------------------------------

class TestDetailedBalance:
    """Verify that symmetrized counts produce detailed-balance-consistent Q."""

    def test_jc_detailed_balance(self):
        alignment, tree, _ = _load_alignment_with_tree(
            os.path.join(DATA_DIR, 'tiny_test.sto'),
            alphabet=['A', 'C', 'G', 'U'],
        )
        A = 4
        Q = np.ones((A, A)) * 1.0
        np.fill_diagonal(Q, -3.0)
        pi = np.ones(A) / A

        result = _compute_subby_counts(alignment, tree, Q, pi, reversible=True)
        new_Q = _m_step_rates(result['waits'], result['mutations'], A)
        new_pi = _stationary_dist(new_Q)

        for i in range(A):
            for j in range(i + 1, A):
                lhs = new_pi[i] * new_Q[i, j]
                rhs = new_pi[j] * new_Q[j, i]
                np.testing.assert_allclose(
                    lhs, rhs, rtol=1e-4,
                    err_msg=f"Detailed balance: {i}<->{j}")

    def test_nullrna_detailed_balance(self):
        alignment, tree, _ = _load_alignment_with_tree(
            os.path.join(DATA_DIR, 'RF00390_trim.sto'),
            alphabet=['A', 'C', 'G', 'U'],
        )
        xg = parse_xrate_file(os.path.join(DATA_DIR, 'nullrna.eg'))
        chain = xg.get_single_models()[0]
        Q = np.array(chain['rate_matrix'])
        pi = np.array(chain['pi'])

        result = _compute_subby_counts(alignment, tree, Q, pi, reversible=True)
        new_Q = _m_step_rates(result['waits'], result['mutations'], 4)
        new_pi = _stationary_dist(new_Q)

        for i in range(4):
            for j in range(i + 1, 4):
                lhs = new_pi[i] * new_Q[i, j]
                rhs = new_pi[j] * new_Q[j, i]
                np.testing.assert_allclose(
                    lhs, rhs, rtol=1e-4,
                    err_msg=f"Detailed balance: {i}<->{j}")
